# -*- mode: python -*-
app_name = 'tebak-huruf-hijaiyah'

import os

block_cipher = None

BASE_PATH = os.getcwd()
RELATIVE_PATH = BASE_PATH+'/'
MAIN_PATH = BASE_PATH+"/main.py"

STATIC_FILES = [
  (RELATIVE_PATH + 'assets/images/tsa-ta-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/3-true.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/heart-pink.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/yeay.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/3-falsepng.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/5-true.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/one-false.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/za.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/qa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/wa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/da.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/alif-ba-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ta-tsa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/game-over.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/salah.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ja-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/lanjut.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/gha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/one-right.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tsa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/main-lagi.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/refresh-arrow.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/na.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/cha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/2-false.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/logout.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ra.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ja.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ya-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tanya-white.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/la.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ya.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/la-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ma-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/2-true.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ta-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ba-ta-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/4-true.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ta.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/heart.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/keluar.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ka.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ra-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/1-unanswered.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/na-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/5-unanswered.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/alif-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ka-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dhla.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/heart-grey.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dhla-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/aa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/fa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/qa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/3-unanswered.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/aa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/alif-tsa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dza-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/5-false.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/2-unanswered.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/masyaAllah.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/profil.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/kho.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/cha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/4-unanswered.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/kho-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ba.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/gha.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dza.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/dha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/da-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/za-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/alif-ta-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/wa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/fa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ba-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tsa.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sya-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/alif.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ma.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tha-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/1-true.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/ba-tsa-ans.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/4-false.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/sya.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/1-false.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/reload.png', 'assets/images'),
  (RELATIVE_PATH + 'assets/images/tanya.png', 'assets/images'),
]

a = Analysis([MAIN_PATH],
             pathex= [BASE_PATH],
             binaries=[],
             datas=STATIC_FILES,
             hiddenimports=['jinja2'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name=app_name,
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name=app_name)
